import type { Inscription } from "./types";

export const corpus: Inscription[] = [
  { id: "i01", words: [["NE", "MA", "DO"], ["NE"], ["gate"]] },
  { id: "i02", words: [["workers"], ["carry"], ["stone"], ["DA"], ["upper"]] },
  { id: "i03", words: [["workers"], ["carry"], ["ME", "KO"], ["DA"], ["upper"]] },
  { id: "i04", words: [["NE", "MA", "DO"], ["DO", "NE"], ["stone"], ["NE"], ["upper"]] },
  { id: "i05", words: [["MO", "NE"], ["NE"], ["upper"]] },
  { id: "i06", words: [["NE", "MA", "DO"], ["NE"], ["lower"], ["gate"]] },
  { id: "i07", words: [["workers"], ["carry"], ["stone"], ["DA"], ["lower"]] },
  { id: "i08", words: [["workers"], ["carry"], ["ME", "KO"], ["DA"], ["lower"]] },
  { id: "i09", words: [["workers"], ["carry"], ["MO", "NE"], ["DA"], ["lower"]] },
  { id: "i10", words: [["MO", "NE"], ["NE"], ["lower"]] },
  { id: "i11", words: [["workers"], ["carry"], ["stone"], ["DA"], ["lower"], ["chamber"]] },
  { id: "i12", words: [["workers"], ["carry"], ["ME", "KO"], ["DA"], ["lower"], ["chamber"]] },
  { id: "i13", words: [["guard"], ["NE"], ["lower"], ["gate"]] },
  { id: "i14", words: [["MO", "NE"], ["NE"], ["lower"], ["chamber"]] },
  { id: "i15", words: [["guard"], ["NE"], ["lower"], ["chamber"]] },
  { id: "i16", words: [["guard"], ["ME"], ["DA", "NO", "ME"], ["workers"], ["DA"], ["DA", "KE"], ["lower"], ["chamber"]] },
  { id: "i17", words: [["workers"], ["ME"], ["DA", "KE"], ["lower"], ["chamber"]] },
  { id: "i18", words: [["NE", "MA", "DO"], ["DA", "KE"], ["lower"], ["chamber"]] },
  { id: "i19", words: [["workers"], ["carry"], ["stone"], ["DA"], ["lower"], ["gate"]] },
  { id: "i20", words: [["MO", "NE"], ["NE"], ["lower"], ["gate"]] },
  { id: "i21", words: [["NE", "MA", "DO"], ["DO", "NE"], ["stone"], ["NE"], ["lower"], ["chamber"]] },
  { id: "i22", words: [["workers"], ["DE", "KA"], ["ME", "KO"], ["NE"], ["upper"]] },
  { id: "i23", words: [["workers"], ["ME"], ["DA", "KE"], ["lower"]] },
  { id: "i24", words: [["NE", "MA", "DO"], ["NA", "DE", "KO"], ["NE"], ["upper"]] },
  { id: "i25", words: [["upper"], ["KO", "ME"]] },
  { id: "i26", words: [["guard"], ["DA", "NO", "ME"], ["workers"], ["DA"], ["DA", "KE"], ["lower"], ["chamber"]] },
  { id: "i27", words: [["workers"], ["DE", "KA"], ["ME", "KO"], ["NE"], ["lower"], ["chamber"]] },
  { id: "i28", words: [["guard"], ["ME"], ["DA", "NO", "ME"], ["workers"], ["DA"], ["DA", "KE"], ["lower"]] },
  { id: "i29", words: [["workers"], ["ME"], ["DA", "KE"], ["lower"]] },
  { id: "i30", words: [["guard"], ["NE"], ["lower"], ["gate"]] },
  { id: "i31", words: [["guard"], ["DA", "MO"], ["lower"], ["chamber"]] },
  { id: "i32", words: [["workers"], ["NA", "DE", "KO"], ["NE"], ["upper"]] },
  { id: "i33", words: [["guard"], ["DA", "MO"], ["lower"], ["gate"]] },
  { id: "i34", words: [["lower"], ["KO", "ME"]] },
];
