import type { Inscription, LexiconEntry } from "./types";

export const corpus: Inscription[] = [
  { id: "i01", words: [["NE", "MA", "DO"], ["NE"], ["gate"]] },
  { id: "i02", words: [["workers"], ["carry"], ["stone"], ["DA"], ["upper"]] },
  { id: "i03", words: [["workers"], ["carry"], ["ME", "KO"], ["DA"], ["upper"]] },
  { id: "i04", words: [["NE", "MA", "DO"], ["DO", "NE"], ["stone"], ["NE"], ["upper"]] },
  { id: "i05", words: [["MO", "NE"], ["NE"], ["upper"]] },
  { id: "i06", words: [["NE", "MA", "DO"], ["NE"], ["lower"], ["gate"]] },
  { id: "i07", words: [["workers"], ["carry"], ["stone"], ["DA"], ["lower"]] },
  { id: "i08", words: [["workers"], ["carry"], ["ME", "KO"], ["DA"], ["lower"]] },
  { id: "i09", words: [["workers"], ["carry"], ["MO", "NE"], ["DA"], ["lower"]] },
  { id: "i10", words: [["MO", "NE"], ["NE"], ["lower"]] },
  { id: "i11", words: [["workers"], ["carry"], ["stone"], ["DA"], ["lower"], ["chamber"]] },
  { id: "i12", words: [["workers"], ["carry"], ["ME", "KO"], ["DA"], ["lower"], ["chamber"]] },
  { id: "i13", words: [["guard"], ["NE"], ["lower"], ["gate"]] },
  { id: "i14", words: [["MO", "NE"], ["NE"], ["lower"], ["chamber"]] },
  { id: "i15", words: [["guard"], ["NE"], ["lower"], ["chamber"]] },
  { id: "i16", words: [["guard"], ["ME"], ["DA", "NO", "ME"], ["workers"], ["DA"], ["DA", "KE"], ["lower"], ["chamber"]] },
  { id: "i17", words: [["workers"], ["ME"], ["DA", "KE"], ["lower"], ["chamber"]] },
  { id: "i18", words: [["NE", "MA", "DO"], ["DA", "KE"], ["lower"], ["chamber"]] },
  { id: "i19", words: [["workers"], ["carry"], ["stone"], ["DA"], ["lower"], ["gate"]] },
  { id: "i20", words: [["MO", "NE"], ["NE"], ["lower"], ["gate"]] },
  { id: "i21", words: [["NE", "MA", "DO"], ["DO", "NE"], ["stone"], ["NE"], ["lower"], ["chamber"]] },
  { id: "i22", words: [["workers"], ["DE", "KA"], ["ME", "KO"], ["NE"], ["upper"]] },
  { id: "i23", words: [["workers"], ["ME"], ["DA", "KE"], ["lower"]] },
  { id: "i24", words: [["NE", "MA", "DO"], ["NA", "DE", "KO"], ["NE"], ["upper"]] },
  { id: "i25", words: [["upper"], ["KO", "ME"]] },
  { id: "i26", words: [["guard"], ["DA", "NO", "ME"], ["workers"], ["DA"], ["DA", "KE"], ["lower"], ["chamber"]] },
  { id: "i27", words: [["workers"], ["DE", "KA"], ["ME", "KO"], ["NE"], ["lower"], ["chamber"]] },
  { id: "i28", words: [["guard"], ["ME"], ["DA", "NO", "ME"], ["workers"], ["DA"], ["DA", "KE"], ["lower"]] },
  { id: "i29", words: [["workers"], ["ME"], ["DA", "KE"], ["lower"]] },
  { id: "i30", words: [["guard"], ["NE"], ["lower"], ["gate"]] },
  { id: "i31", words: [["guard"], ["DA", "MO"], ["lower"], ["chamber"]] },
  { id: "i32", words: [["workers"], ["NA", "DE", "KO"], ["NE"], ["upper"]] },
  { id: "i33", words: [["guard"], ["DA", "MO"], ["lower"], ["gate"]] },
  { id: "i34", words: [["lower"], ["KO", "ME"]] },
];

export const lexicon: LexiconEntry[] = [
  { english: "absent", yot: "NA-DE-KO" },
  { english: "allow", yot: "DA-NO-ME" },
  { english: "at", yot: "NO" },
  { english: "carry", yot: "DO-KO" },
  { english: "chamber", yot: "KE-NA-DO" },
  { english: "complete", yot: "KO-ME" },
  { english: "cut", yot: "DE-KA" },
  { english: "enter", yot: "DA-KE" },
  { english: "food", yot: "MO-NE" },
  { english: "foreman", yot: "NE-MA-DO" },
  { english: "gate", yot: "MA-KE" },
  { english: "guard", yot: "NA-MO" },
  { english: "in", yot: "NE" },
  { english: "lower", yot: "DE-MO" },
  { english: "messenger", yot: "NA-ME-DO" },
  { english: "not", yot: "ME" },
  { english: "rope", yot: "NE-KO" },
  { english: "seal", yot: "DA-MO" },
  { english: "set", yot: "DO-NE" },
  { english: "stone", yot: "NO-KA" },
  { english: "throw", yot: "DO-NA" },
  { english: "to", yot: "DA" },
  { english: "upper", yot: "KO-DA" },
  { english: "wood", yot: "ME-KO" },
  { english: "workers", yot: "KA-NO" },
];
